apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  labels:
    app: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-default-agent-0  # same node as PV
      volumes:
        - name: shared-pv
          persistentVolumeClaim:
            claimName: pinglog-pvc
      containers:
        - name: ping-pong
          image: ping-pong:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: DATA_DIR
              value: "/shared"
          volumeMounts:
            - name: shared-pv
              mountPath: /shared
          ports:
            - containerPort: 8080

