apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app:1.3              # <-- updated tag
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"                 # change to test other ports
            - name: GREETING
              value: "Hello from Kubernetes 👋"
          ports:
            - containerPort: 8080           # informational
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

