apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"   # <- kube-prometheus-stack Grafana sidecar watches this
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy           # <- this is the “Server” mode
      url: http://loki:3100
      isDefault: false

