apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-todo
  namespace: project
spec:
  schedule: "0 * * * *"   # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-todo
            image: wiki-todo:1.0
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc/api/todos"
          restartPolicy: OnFailure

