apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-images-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: todo-images-pv

