apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: writer
        image: log-writer:0.1
        env:
        - name: DATA_DIR
          value: /data
        - name: INTERVAL_SECONDS
          value: "5"
        volumeMounts:
        - name: shared
          mountPath: /data
      - name: reader
        image: log-reader:0.5
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DATA_DIR
          value: /data
        - name: PINGPONG_URL
          value: http://ping-pong-svc/pings
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-output-config
              key: MESSAGE
        volumeMounts:
        - name: shared
          mountPath: /data
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: shared
        emptyDir: {}
      - name: config-volume
        configMap:
          name: log-output-config
          items:
          - key: information.txt
            path: information.txt

