apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-default-agent-0
      volumes:
        - name: shared-pv
          persistentVolumeClaim:
            claimName: pinglog-pvc
      containers:
        - name: writer
          image: log-writer:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_DIR
              value: "/data"
            - name: INTERVAL_SECONDS
              value: "5"
          volumeMounts:
            - name: shared-pv
              mountPath: /data
        - name: reader
          image: log-reader:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: DATA_DIR
              value: "/data"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: shared-pv
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5

