apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels: { app: todo-backend }
  namespace: project
spec:
  replicas: 1
  selector: { matchLabels: { app: todo-backend } }
  template:
    metadata: { labels: { app: todo-backend } }
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:1.0
          imagePullPolicy: IfNotPresent
          env: [{ name: PORT, value: "8080" }]
          ports: [{ name: http, containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 2
            periodSeconds: 5

